### ISSUE TITLE
How To Work?

### ISSUE THREAD

**Issue by R3DEYEDJ3D1** [kibook/redm-objectloader#1]
how do I get object loader to work? 
I have put my .xml file in the maps folder but when I load my server up, it doesn't load my map.
Can you please provide a walkthrough or guide on how to get this to work?

**Comment by kibook** [comment]
I will definitely add something to the README. There's also an example map in the repository that you could use as a starting point: https://github.com/kibook/redm-objectloader/tree/master/%5Bmaps%5D/example

Each map is its own resource, so it should be in a subfolder in `[maps]` with a resource manifest like this:
```
fx_version 'adamant'
game 'rdr3'
rdr3_warning 'I acknowledge that this is a prerelease build of RedM, and I am aware my resources *will* become incompatible once RedM ships.'

dependency 'objectloader'

files {
	'mymap.xml'
}

objectloader_map 'mymap.xml'
```

**Comment by kibook** [comment]
Added an example of creating a resource for a map to [README.md](https://github.com/kibook/redm-objectloader/blob/ae79cc6abe230710a14033957d96bc31a578d913/README.md): ae79cc6

Let me know if that helps!

**Comment by R3DEYEDJ3D1** [comment]
It wasn't working for me until I moved the object loader from resources to [Local] but now it is working perfectly and you have saved me soooooo much time, Thankyou very much 👍
