### ISSUE TITLE
Error to load maps FFFFFFF

### ISSUE THREAD

**Issue by Victorcin** [kibook/redm-objectloader#2]
Hello @kibook ,have been using the tool for a few weeks and during this week, some maps that I have loaded on the server, certain clients get this error when reloading the map entities.

![image](https://user-images.githubusercontent.com/10252866/108610261-b57c1100-73d4-11eb-9409-f970f31a46ed.png)

![image](https://user-images.githubusercontent.com/10252866/108610288-e2302880-73d4-11eb-8ab2-7412a4c051b7.png)

I've been checking but haven't found a solution.

PD: use redm-object-spooner to create.

Thanks and hope someone help.

**Comment by kibook** [comment]
From what I can tell, the error seems to occur when you spawn too many objects at once. Do you have a lot of maps that are close together with lots of objects? objectloader will despawn objects when you get far away enough (`Config.SpawnDistance`), but if you have many maps close together, they'll all be loaded at the same time.

I don't know if there's a way to get a hard number on how many objects is "too many" for the game, but I can maybe experiment with adding a limit to how many objects objectloader will spawn at the same time across all maps. This will mean some maps might not load completely if you're hitting that limit, but it should prevent that error from occurring.

**Comment by kibook** [comment]
I added a new configuration setting in 5cd2fed, `Config.MaxEntities`, which specifies a maximum number of entities that are allowed to be spawned by objectloader at the same time across all maps. The default is 300, which I found to be a safe limit while testing some big maps that I know normally cause the FFFFFFF error (particularly, this one: https://www.nexusmods.com/reddeadredemption2/mods/253). Around 350-400+ is where I started getting the error, though it's possible the number will vary based on the number of entities already around from the game/other scripts.

With this in place, I'm not getting the FFFFFFF error, but if there are more than 300 entities between maps that need to be spawned at the same time, some of them won't be spawned. It will print an error message in the console (F8):
```
Max entity limit (300) has been reached. Please reduce the number of entities in your maps.
```
[![](https://i.imgur.com/Ghl6IbFm.jpg)](https://imgur.com/Ghl6IbF)

Let me know if this seems to reduce/remove the error for you, and maybe also try tweaking `Config.MaxEntities` and/or `Config.SpawnDistance` if it doesn't. A lower `Config.SpawnDistance` can help if you have maps with lots of entities close to each other, though the downside is the object "pop in" will be more noticeable.

**Comment by Victorcin** [comment]
We have been testing with the new version and we have verified that when loading the map for the first time, cleaning the entities will erase some objects that were already on the map.

I understand that when updating the map it deletes its own entities from the map and also each client sees duplicates all the objects placed on each custom map each time it is reloaded.

This causes the total to pass and effectively gives the FFFFFF error.

I think that deleting the entities is not deleting them correctly when updating the map.


When load map delete someone objects: ( Post,Doors,Windows...)

![image](https://user-images.githubusercontent.com/10252866/108636029-0d715100-7483-11eb-88c4-ba9831bbc8e0.png)
![image](https://user-images.githubusercontent.com/10252866/108636032-14985f00-7483-11eb-83e7-3ac9078e08cf.png)

**Comment by kibook** [comment]
> We have been testing with the new version and we have verified that when loading the map for the first time, cleaning the entities will erase some objects that were already on the map.

Nearby entities would be deleted when objectloader itself was started/stopped, or if the thread for a map crashed. If it was deleting nearby objects when starting a map, check the F8 console in-game to see if a message like `Restarting map [map name]...` appears, which indicates the thread for that map crashed or timed out.

This was done as a workaround for some other issues, but wasn't a very good solution, so I think I've replaced it with something better in 688ec6a.

> I understand that when updating the map it deletes its own entities from the map and also each client sees duplicates all the objects placed on each custom map each time it is reloaded.

> This causes the total to pass and effectively gives the FFFFFF error.

> I think that deleting the entities is not deleting them correctly when updating the map.

I haven't been getting the FFFFFFF error since the last update, as far as I can tell it is successfully deleting every entity it spawns. It's possible the number of objects created by the game may count towards the "limit", and obviously if you have other scripts spawning objects, those would count, too. Did you try lowering `Config.MaxEntities` to see if that helped?

If a particular map seems to be consistently giving you issues, if you can provide the map XML I would be happy to test it.

**Comment by Victorcin** [comment]
Hello @kibook with new versión now works maps and the error FFFFF dont show anymore,so is great! 
Also now only delete entities of map ✅
Will continue testing more thoroughly and I will tell you if I find any more errors. Thank you very much for the help and great tool!
Regards my friend.
